### ISSUE TITLE
Contributing guidelines

### ISSUE THREAD

**Issue by DavidSantacruzR** [gftea/amqprs#40]
Hi @gftea, I'm fairly new to rust (dev. moving from python to rust), and I was just checking some projects related to rabbitMQ, and rust. I have to say that your project is the best one I've found so far (Really well documented!).

So, I wonder are there any contributing guidelines that one must follow when contributing?

**Comment by gftea** [comment]
@DavidSantacruzR , glad to receive our feedbacks!
Sorry, I did not write any contribution guidelines, in general, you can use Discussions/Issues/Pull Requests for different purpose

For bug report and feature request, just open an issue for it, so that PR can have a issue ticket to refer.
Otherwise, use **Discussions** for others

**Comment by DavidSantacruzR** [comment]
Thanks for the response, I'll keep this in mind when contributing to the project, and again awesome work!
